services:
  db:
    image: postgres:15-alpine
    restart: unless_stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zer0bin
      POSTGRES_DB: postgres
    volumes:
      - ./db/:/var/lib/postgresql/data

  api:
    image: ghcr.io/angeloanan/zer0bin-backend:dev
    # UNLESS YOU WANT TO BUILD FROM SOURCE
    # build:
    #   dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    image: ghcr.io/angeloanan/zer0bin-frontend:dev
    # UNLESS YOU WANT TO BUILD FROM SOURCE
    # build:
    #   dockerfile: Dockerfile.frontend
    ports:
      - "80:59046"
    depends_on:
      - api
    # volumes:
    # - ./default.nginx:/etc/nginx/conf.d/default.conf - Only if you want to change the nginx config
